/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n5.1-10-g6ee1996721-20220822"
#endif /* AVUTIL_FFVERSION_H */
